---
title: "7.テンプレートの利用"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# 1 Rコードの利用

```{r}
library(dplyr)
library(ggplot2)
```

## 1.1 データの確認
```{r}
head(iris)
```

<br><br>

## 1.2 データの可視化

```{r}
iris %>%
  ggplot(aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme_classic(base_family = "HiraKakuPro-W3") +
  theme(text=element_text(size=30)) +
  labs(title="プロット")
```

<br><br><br>

# 2 Rコードの利用{.tabset}

```{r}
library(dplyr)
library(ggplot2)
```

<br><br>

## 2.1 データの確認
```{r}
head(iris)
```

<br><br>

## 2.2 データの可視化

```{r}
iris %>%
  ggplot(aes(Sepal.Length, Sepal.Width)) +
  geom_point() +
  theme_classic(base_family = "HiraKakuPro-W3") +
  theme(text=element_text(size=30)) +
  labs(title="プロット")
```
